In [2]:
pip install tensorflow

Verify Install

In [3]:
import tensorflow as tf
print(tf.__version__)

2.19.0


Create tensor

In [12]:
a=tf.constant(10)
print(a)
v=tf.constant([1,2,3,4])
print(v)

m=tf.constant([[1,2],[3,4]])
print(m)

t3=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(t3)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]], shape=(1, 4, 2), dtype=int32)


Scalar Addition,Subration,Multiplicaton,Division,ppower

In [18]:
a=tf.constant(24)
b=tf.constant(26)
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))
print(tf.pow(a,b))

tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(-2, shape=(), dtype=int32)
tf.Tensor(624, shape=(), dtype=int32)
tf.Tensor(0.9230769230769231, shape=(), dtype=float64)
tf.Tensor(0, shape=(), dtype=int32)


Tensor performance on 2D

In [16]:
a=tf.constant([10,20,30])
b=tf.constant([34,2,7])
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))

tf.Tensor([44 22 37], shape=(3,), dtype=int32)
tf.Tensor([-24  18  23], shape=(3,), dtype=int32)
tf.Tensor([340  40 210], shape=(3,), dtype=int32)
tf.Tensor([ 0.29411765 10.          4.28571429], shape=(3,), dtype=float64)


Tensor performance on 3D

In [22]:
a=tf.constant([[10,20],[76,13]])
b=tf.constant([[34,2],[35,5]])
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))

tf.Tensor(
[[ 44  22]
 [111  18]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-24  18]
 [ 41   8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 340   40]
 [2660   65]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0.29411765 10.        ]
 [ 2.17142857  2.6       ]], shape=(2, 2), dtype=float64)


datatype and shape of tensor

In [19]:
a= tf.constant([10,20,30])
print(a.dtype,a.shape,tf.rank(a))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)


Numpy array to tensor

In [23]:
import numpy as np
np_array=np.array([[1,2,3],[4,5,6]])
print(np_array)
tensor=tf.convert_to_tensor(np_array)
print(tensor)

[[1 2 3]
 [4 5 6]]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
