In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense


In [ ]:
corpus = [
    "Artificial intelligence is changing the world in many ways.",
"Machine learning helps computers learn from data.",
"Deep learning is a subset of machine learning.",
"Neural networks are inspired by the human brain.",
"A dataset is used to train a machine learning model.",
"Training data should be clean and well organized.",
"A model learns patterns from examples in the dataset.",
"LSTM stands for Long Short Term Memory.",
"LSTM is a special type of recurrent neural network.",
"Recurrent neural networks are useful for sequence data.",
"Text generation is a common application of LSTM models.",
"Natural language processing deals with human language.",
"Words are converted into numbers before model training.",
"Tokenization is the process of splitting text into words.",
"Each word can be mapped to a unique integer.",
"Sequences are created from the tokenized text.",
"Padding is used to make all sequences the same length.",
"The model predicts the next word in a sequence.",
"Loss decreases as the model learns better patterns.",
"Accuracy may improve over multiple training epochs.",
"An epoch means one full pass through the dataset.",
"Batch size controls how many samples are processed together.",
"The optimizer updates model weights during training.",
"Adam is a popular optimizer in deep learning.",
"Categorical crossentropy is often used for text prediction.",
"Embedding layers help represent words in dense vectors.",
"Dense vectors capture semantic relationships between words.",
"The hidden state stores useful information over time.",
"Memory cells allow LSTM to remember past context.",
"Forget gates decide what information should be removed.",
"Input gates decide what new information should be stored.",
"Output gates decide what information should be passed on.",
"A trained model can generate meaningful text sequences.",
"Prediction quality depends on data quality and model design.",
"More training data often improves the performance of the model.",
"Overfitting happens when the model memorizes the training data.",
"Validation data helps check model performance during training.",
"Testing data is used to evaluate the final model.",
"Python is commonly used for machine learning projects.",
"TensorFlow is a popular deep learning framework.",
"Keras provides a simple interface for building neural networks.",
"The tokenizer builds a vocabulary from the training corpus.",
"Vocabulary size affects the complexity of the model.",
"The sequence length determines how much context is used.",
"Longer sequences may capture more meaning in text.",
"Shorter sequences train faster but may lose context.",
"Preprocessing is an important step in any machine learning pipeline.",
"A good corpus should contain meaningful and varied sentences.",
"Consistent grammar helps the model learn better patterns.",
"Text generation can be creative and educational.",
"LSTM models are useful for learning sequential dependencies."
]
print("Number of sentences:", len(corpus))

Number of sentences: 51


In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)

word_index = tokenizer.word_index
total_words = len(word_index) + 1
print("Vocabulary size:", total_words)
print("\nWord index:")
print(word_index)

Vocabulary size: 212

Word index:
{'the': 1, 'is': 2, 'a': 3, 'model': 4, 'learning': 5, 'data': 6, 'training': 7, 'in': 8, 'text': 9, 'of': 10, 'are': 11, 'used': 12, 'be': 13, 'for': 14, 'machine': 15, 'to': 16, 'should': 17, 'lstm': 18, 'sequences': 19, 'from': 20, 'neural': 21, 'and': 22, 'words': 23, 'information': 24, 'helps': 25, 'deep': 26, 'networks': 27, 'dataset': 28, 'patterns': 29, 'useful': 30, 'sequence': 31, 'can': 32, 'may': 33, 'context': 34, 'gates': 35, 'decide': 36, 'what': 37, 'many': 38, 'learn': 39, 'human': 40, 'train': 41, 'learns': 42, 'memory': 43, 'recurrent': 44, 'generation': 45, 'models': 46, 'language': 47, 'into': 48, 'word': 49, 'length': 50, 'better': 51, 'over': 52, 'an': 53, 'size': 54, 'how': 55, 'optimizer': 56, 'during': 57, 'popular': 58, 'often': 59, 'prediction': 60, 'dense': 61, 'vectors': 62, 'capture': 63, 'on': 64, 'meaningful': 65, 'quality': 66, 'more': 67, 'performance': 68, 'vocabulary': 69, 'corpus': 70, 'artificial': 71, 'intelligen

In [ ]:
input_sequences = []

for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_seq = token_list[:i+1]
        input_sequences.append(n_gram_seq)

print("Total training sequences:", len(input_sequences))
print("\nSome sequences before padding:")
for seq in input_sequences[:10]:
    print(seq)

Total training sequences: 374

Some sequences before padding:
[71, 72]
[71, 72, 2]
[71, 72, 2, 73]
[71, 72, 2, 73, 1]
[71, 72, 2, 73, 1, 74]
[71, 72, 2, 73, 1, 74, 8]
[71, 72, 2, 73, 1, 74, 8, 38]
[71, 72, 2, 73, 1, 74, 8, 38, 75]
[15, 5]
[15, 5, 25]


In [ ]:
max_seq_len = max(len(seq) for seq in input_sequences)
input_sequences = pad_sequences(input_sequences, maxlen=max_seq_len, padding='pre')

print("Maximum sequence length:", max_seq_len)
print("\nPadded sequences:")
print(input_sequences[:10])

Maximum sequence length: 10

Padded sequences:
[[ 0  0  0  0  0  0  0  0 71 72]
 [ 0  0  0  0  0  0  0 71 72  2]
 [ 0  0  0  0  0  0 71 72  2 73]
 [ 0  0  0  0  0 71 72  2 73  1]
 [ 0  0  0  0 71 72  2 73  1 74]
 [ 0  0  0 71 72  2 73  1 74  8]
 [ 0  0 71 72  2 73  1 74  8 38]
 [ 0 71 72  2 73  1 74  8 38 75]
 [ 0  0  0  0  0  0  0  0 15  5]
 [ 0  0  0  0  0  0  0 15  5 25]]


In [ ]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

y = tf.keras.utils.to_categorical(y, num_classes=total_words)

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (374, 9)
Shape of y: (374, 212)


In [ ]:
model = Sequential([
    Embedding(input_dim=total_words, output_dim=10, input_length=max_seq_len - 1),
    LSTM(50),
    Dense(total_words, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.0241 - loss: 5.3547
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0535 - loss: 5.3415
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0535 - loss: 5.3049
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0401 - loss: 5.1358
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0374 - loss: 4.9587
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0455 - loss: 4.9134
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0481 - loss: 4.8849
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0481 - loss: 4.8717
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0481 - loss: 4.8631
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0481 - loss: 4.8486
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0642 - loss: 4.8377
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - ac

In [ ]:

def generate_text(seed_text, next_words):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_seq_len - 1, padding='pre')

        predicted_probs = model.predict(token_list, verbose=0)
        predicted_index = np.argmax(predicted_probs, axis=-1)[0]

        output_word = ""
        for word, index in tokenizer.word_index.items():
            if index == predicted_index:
                output_word = word
                break

        seed_text += " " + output_word
    return seed_text

In [ ]:
print(generate_text("LSTM is ", 5))
print(generate_text("machine learning", 2))
print(generate_text("python is", 2))

LSTM is  a to for machine learning
machine learning is a
python is a to


In [ ]:
print(generate_text("artificial intelligence is ", 5))
print(generate_text("data science", 2))
print(generate_text("lstm is used for", 3))

artificial intelligence is  a for of learning learning
data science is a
lstm is used for information in learning
